lib/thamani_web/router.ex
      get("/:security_key/:user_id/:id", InventoryApiController, :show)
      post("/", InventoryApiController, :create)
      delete("/:id", InventoryApiController, :delete)
      put("/:id", InventoryApiController, :update)
    end

    scope "/push_sale" do
      pipe_through([:api])
      get("/:user_id", SaleApiController, :index)
      get("/:user_id/:id", SaleApiController, :show)
      post("/", SaleApiController, :create)
      delete("/:id", SaleApiController, :delete)
      put("/:id", SaleApiController, :update)
    end

    scope "/credit_note" do
      pipe_through([:api])
      get("/:security_key/:user_id", CreditnoteApiController, :index)
      get("/:security_key/:user_id/:id", CreditnoteApiController, :show)
      post("/", CreditnoteApiController, :create)
    end

    scope "/staff/retailer" do
      pipe_through([:api])
      get("/:security_key", StaffApiController, :index)
      get("/:security_key/:phone/:passcode", StaffApiController, :show)
      post("/", StaffApiController, :create)
      delete("/:id", StaffApiController, :delete)
      put("/:id", StaffApiController, :update)
    end

    scope "/device/retailer" do
      pipe_through([:api])
      get("/:security_key", DeviceApiController, :index)
      get("/:security_key/:imei", DeviceApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:api])

      get("/validate", ValidateApiController, :index)
      post("/validate", ValidateApiController, :create)
      post("/balance", BalanceApiController, :create)
      post("/status", MpesaStatusController, :create)
    end

    scope "/commerce" do
      pipe_through([:api])


      post("/cart", CommerceApiController, :create)
      post("/status", CommerceApiController, :status)
      post("/update", CommerceApiController, :updatecart)
      post("/del", CommerceApiController, :delcart)

    end

    scope "/stkpush" do
      pipe_through([:api])

      get("/validate", MpesaApiController, :index)
      post("/", MpesaApiController, :create)
      get("/validate/:params", MpesaApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:browser])
      resources("/sms/", SmsApiController)
      resources("/confirmation", ConfirmationController)
    end

    scope "/api/sale_url/v1" do
      pipe_through([:api])
      get("/:security_key", SaleDashboardApiController, :index)
      get("/:security_key/:account_number", SaleDashboardApiController, :show)
      post("/", SaleDashboardApiController, :create)
    end

    pipe_through([:browser, :with_session])

    get("/", PageController, :index)
    get("/privacy", PrivacyController, :index)
    get("/terms", TermsController, :index)
    resources("/register", RegisterController)
    resources("/login", LoginController, only: [:index, :create, :delete])

    resources(
      "/forgot_password",
      ResetController,
      only: [:index, :new, :create, :edit, :update, :delete]
    )

    scope "/" do
      pipe_through([:login_required])

      resources("/validation/", PaymentApiController)
      get("/panel", PanelController, :index)
      resources("/locations", LocationsController)
      resources("/sms_reset/", SmsResetController)
      resources(
        "/users",
        ChangePassController,
        only: [:update]
      )
      resources("/users", UserController)
      resources("/verify", VerifyController)

      # manufacturer panel
      resources("/manufacturer/dashboard/status", ManufacturerDashboardController)
      resources("/item", ItemController)
      resources("/batch", BatchController)
      resources("/manufacturer/dispatch/warehouse", DispatchController)
      resources("/manufacturer/dispatch/retailer", DispatchRetailerController)
      resources("/orders/warehouse/items", OrdersManufacturerController)
      resources("/orders/retail/items", OrdersRetmanController)
      resources("/invoice", InvoiceController)
      resources("/manufacturer/reorders/items", ReorderManufacturerController)
      resources("/manufacturer/sales/status", SalesManufacturerController)
      resources("/manufacturer/warehouse/returns", WreturnController)
      resources("/manufacturer/retailer/returns", RreturnController)
      resources("/manufacturer/warehouse/stock", StockManufacturerController)
      resources("/manufacturer/retailer/stock", StockRetmanController)


      resources "/manufacturer", UserController, only: [:show] do
        resources("/code", CodesController)
        resources("/company", CompanyController)
      end

      # warehouse Panel
      resources("/warehouse/dashboard/status", WarehouseDashboardController)
      resources("/invoice_warehouse", InvoiceWarehouseController)
      resources("/orders", OrdersWarehouseController)
      resources("/warehouse/recieved/items", RecievedController)
      resources("/storage", StorageController)
      resources("/break_bulk", BreakbulkController)
      resources("/warehouse/sales/status", SalesWarehouseController)
      resources("/dispatch", DispatchWarehouseController)
      resources("/manufacturer/order/items", ManufacturerOrdersController)
      resources("/returns", ReturnController)
      resources("/warehouse/reorders/items", ReorderWarehouseController)
      resources("/warehouse/retailer/stock", StockWarehouseController)

      # retailer panel
      resources("/retail/dashboard/status", RetailDashboardController)
      resources("/invoice_retailer", InvoiceRetailController)
      resources("/retailer/sales/status", SaleController)
      resources("/retailer/recieved/manufacturer", RecievedRetmanController)
      resources("/retailer/recieved/warehouse", RecievedRetailerController)
      resources("/inventory", InventoryController)
      resources("/inventory_manufacturer", Inventory2Controller)
      resources("/warehouse/orders/items", WarehouseOrdersController)
      resources("/retailer/orders/items", RetmanOrdersController)
      resources("/warehouse/returns/status", RetailReturnController)
      resources("/retailer/reorder/items", ReorderController)
      resources("/discount", DiscountController)
      resources("/credit_note", NotesController)
      resources("/staff", StaffController)
      resources("/shop", ShopController)
      resources("/device", DeviceController)

      # commerce Dashboard

      resources("/order", CommerceController)
      # get("/completed", CommerceController, :orders)
      resources("/commerce", CommsController)

      get("/completed", CommsController, :orders)

      # sales Dashboard

      resources("/sales/dashboard/status", SaleDashboardController)

      # admin zone GS1 Dashboard
      resources("/admin/thamani/dashboard", Gs1DashboardController)
      resources("/admin/thamani/price_master", PmasterController)
      resources("/admin/thamani/reconciliation", ReconcileController,only: [:index])
      resources("/admin/thamani/mpesa_transactions", MpesaController)

      # admin manufacturer
      resources("/admin/dashboard", ManufacturerAdminDashboardController)
      resources("/admin/item", ItemAdminController)
      resources("/admin/batch", BatchAdminController)
      resources("/admin/barcode", BarcodeController)
      resources("/admin/dispatch", DispatchAdminController)
      resources("/admin/dispatch_retailer/", DispatchRetailerAdminController)
      resources("/admin/warehouse/orders/all", OrdersAdmManufacturerController)
      resources("/admin/retail/orders/all", OrdersAdminRetmanController)
      resources("/admin/sales", SalesAdminManufacturerController)
      resources("/admin/reorder", ReorderAdminController)
      resources("/admin/manufacturer/warehouse/returns", WreturnAdminController)
      resources("/admin/manufacturer/retailer/returns", RreturnAdminController)

      # admin warehouse
      resources("/admin/warehouse/dashboard", WarehouseAdminDashboardController)
      resources("/admin/warehouse/recieved", RecievedAdminController)
      resources("/admin/warehouse/storage", StorageAdminController)
      resources("/admin/warehouse/break_bulk", BreakbulkAdminController)
      resources("/admin/warehouse/dispatch", DispatchAdminWarehouseController)
      resources("/admin/warehouse/manufacturer/orders", ManufacturerAdmOrdersController)
      resources("/admin/warehouse/manufacturer/returns", ReturnAdminController)
      resources("/admin/retailer/orders", OrdersAdmWarehouseController)

      # admin retailer
      resources("/admin/retailer/dashboard", RetailAdminDashboardController)
      resources("/admin/retailer/recieved", RecievedAdminRetailerController)
      resources("/admin/retailer/inventory", InventoryAdminController)
      resources("/admin/retailer/sales", SaleAdminController)
      resources("/admin/retailer/staff", StaffAdminController)
      resources("/admin/manufacturer/orders", RetmanAdminOrdersController)
      resources("/admin/retailer/shop", ShopAdminController)
      resources("/admin/retailer/device", DeviceAdminController)
      resources("/admin/retailer/discount", DiscountAdminController)
      resources("/admin/credit_note", NotesAdminController)
      resources("/admin/retailer/warehouse/orders", WarehouseAdmOrdersController)
      resources("/admin/retailer/returns", RetailAdminReturnController)

      # float panel

      resources("/float/dashboard", FloatDashboardController)
      resources("/float/credit", FloatController)

      resources "/float", UserController, only: [:show] do
        resources("/debit", DebitController)
      end

      # float admin panel
      resources("/admin/float/credit", FloatAdminController)
      resources("/admin/float/debit", DebitAdminController)
      resources("/admin/float/dashboard", FloatAdminDashboardController)

      # admin zone
      scope "/admin", Admin, as: :admin do
        pipe_through([:admin_required])

        resources "/users", UserController, only: [:index, :show] do
        end
      end
    end
  end

  # Other scopes may use custom stacks.

lib/thamani_web/controllers/reorder_admin_controller.ex
defmodule ThamaniWeb.ReorderAdminController do
  use ThamaniWeb, :controller
  require Ecto.Query
  require Ecto
  use Ecto.Schema
  alias Thamani.Inventories

  alias Thamani.Dispatches_Warehouse
  alias Thamani.Dispatches_Retailer

  alias Thamani.Reorders

  plug(:put_layout, "retail.html")
  plug(:scrub_params, "inventory" when action in [:create, :update])

  def index(conn, _params) do
    reorder = Reorders.list_reorders()
    count_4 = Inventories.get_count_restock_man_all()
    count_5 = Dispatches_Warehouse.get_count_recieved_all!()
    count_6 = Dispatches_Retailer.get_count_recieved_all!()

    render(
      conn,
      "index.html",
      reorder: reorder,
      count_4: count_4,
      count_5: count_5,
      count_6: count_6
    )
  end

  def show(conn, %{"id" => id}) do
    count_4 = Inventories.get_count_restock_man_all()
    count_5 = Dispatches_Warehouse.get_count_recieved_all!()
    count_6 = Dispatches_Retailer.get_count_recieved_all!()
    reorder = Reorders.get_reorder!(id)

    render(
      conn,
      "show.html",
      reorder: reorder,
      count_4: count_4,
      count_5: count_5,
      count_6: count_6
    )
  end
end

lib/thamani_web/views/reorder_admin_view.ex
defmodule ThamaniWeb.ReorderAdminView do
  use ThamaniWeb, :view
  use Rummage.Phoenix.View
end

lib/thamani_web/templates/reorder_admin/edit.html.eex
<span class="col-md-10" style="margin-left: -25px;"> <%= link "Back", to: reorder_admin_path(@conn, :index),class: "btn btn-gold btn-gold"  %></span>

<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">Company</h4>
        <p class="category"><%= link "Dashboard", to: retail_admin_dashboard_path(@conn, :index) %>/ reorder/edit</p>

    </div>
<%= render "form.html", Map.put(assigns, :action, reorder_admin_path(@conn, :update, @reorder)) %>

lib/thamani_web/templates/reorder_admin/form.html.eex
<%= form_for @changeset, @action, [multipart: true] , fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="col-md-6">
  <div class="form-group label-floating">
    <%= label f, :"Inventory", class: "control-label" %>
    <%= select f, :item, @bat , class: "selectpicker", "data-style": "btn btn-gold btn-round", disabled: "disabled",title: "Choose item" , required: "required"%>
      </div>
    <%= error_tag f, :item %>
  </div>

  <div class="col-md-6">
    <div class="form-group label-floating">
    <%= label f, :price, class: "control-label" %>
    <%= text_input f, :price, disabled: "disabled",class: "form-control" %>
      </div>

    <%= error_tag f, :price %>
  </div>

  <div class="col-md-10">
  <div class="form-group label-floating">
    <%= label f, :Category, class: "control-label" %>
      <%= select f, :category,  ["Beverages": "Beverages","Bread/Bakery": "Bread/Bakery", "Canned/Jarred Goods": "Canned/Jarred Goods", "Dairy": "Dairy", "Dry/Baking Goods": "Dry/Baking Goods", "Frozen Foods": "Frozen Foods", "Meat": "Meat", "Fruits/vegetables": "Fruits/vegetables", "Cleaning products": "Cleaning products","Hygiene products": "Hygiene products",
      "Cosmetics ": "Cosmetics", "Confections & Candies": "Confections & Candies", "Houseware & Utensils": "Houseware & Utensils",
       "Toys & novelties": "Toys & novelties", cards: "cards", "Paper Goods": "Paper Goods", "Personal Care": "Personal Care", "Pet foods & products": "Pet foods & products", "Medicinal": "Medicinal", "Tools": "Tools", "Others": "Others", "Others": "Others"] , class: "selectpicker", "data-style": "btn btn-gold btn-round", title: "Choose Category" ,disabled: "disabled", required: "required"%>
  </div>
    <%= error_tag f, :category %>
  </div>

  <div class="col-md-10">
    <div class="form-group label-floating">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, disabled: "disabled",class: "form-control" %>
      </div>
    <%= error_tag f, :description %>
  </div>

  <div class="col-md-10">
    <div class="form-group label-floating">

    <%= label f, :"Confirm Re-order", class: "control-label" %>
    <%= checkbox f, :confirm, class: "checkbox-material" %>
      </div>
    <%= error_tag f, :confirm %>
  </div>

  <div class="col-md-6">
    <div class="form-group label-floating">
    <%= submit "Submit", class: "btn btn-gold" %>
  </div>
    </div>
<% end %>

lib/thamani_web/templates/reorder_admin/index.html.eex
                                            <div class="row">
                                                                   <div class="col-md-12">
                                                                         <div class="card">
                                                                           <div class="card-header" data-background-color="gold">
                                                                               <h4 class="title">Reorder</h4>

                                                                           </div>

                                                                           <div class="card-content table-responsive">
                                                                             <div id="toolbar" style="margin-top: -16px;">
                                                                            <select class="form-control">
                                                                              <option value="">Export Current page</option>
                                                                              <option value="all">Export All</option>
                                                                              <option value="selected">Export Selected</option>
                                                                            </select>
                                                                          </div>
                                          <table class="table" id ="fresh-table" data-toggle="table" data-toolbar="#toolbar" data-search="true"  data-pagination="true" data-show-print="true" data-show-export="true"   data-export-options='{"fileName": "reports"}'>
                                              <thead class="text-info">
                                                <tr>
                                                  <th data-field="state" data-checkbox="true"></th>
                                                  <th data-field="retailer" data-sortable="true">Retailer </th>
                                                  <th data-field="sku" data-sortable="true">SKU Item</th>
                                                  <th data-field="qty" data-sortable="true">Quantity</th>
                                                  <th data-field="name" data-sortable="true">Order from</th>
                                                  <th data-field="man" data-sortable="true">which Manufacturer</th>
                                                  <th data-field="ware" data-sortable="true">Which Warehouse</th>
                                                  <th data-field="desc" data-sortable="true">Description</th>

                                                  <th class="text-center" >Status</th>
      <th class="text-center"> Actions</th>
    </tr>
  </thead>
  <tbody>
<%= for reorder <- @reorder do %>
    <tr>
      <td></td>
      <td><%= reorder.user.company %> </td>
      <td><%= reorder.sku.name %> </td>
      <td><%= reorder.quantity %> </td>
      <td><%= reorder.type %> </td>
      <td> <%= reorder.manufacturer.company%></td>
        <%= if reorder.wid == 0 do %>
          <td>N/A</td>
         <% else  %>
         <td><%= reorder.warehouse.company %> </td>
           <% end %>

      <td><%= reorder.description %> </td>
      <%= if reorder.active == "true" do %>
      <td><p class = "btn btn-success btn-success" >Recieved</p></td>
        <% else  %>
        <td><p class = "btn btn-info btn-info" >Pending</p></td>
          <% end  %>
      <td class="text-right">
                                                  <span  rel="tooltip" title="View Task" class="btn btn-info btn-simple ">
                                                      <span ><%= link "",  to: reorder_admin_path(@conn, :show,  reorder), class: "fa fa-search-plus" ,style: "color:#00bcd4 !important" %></span>
                                                  </span>



</td>

    </tr>
<% end %>
  </tbody>
</table>
</div>
                                                        </div>
                                                      </div>
                                                    </div>

lib/thamani_web/templates/reorder_admin/new.html.eex
<span class="col-md-10" style="margin-left: -25px;"> <%= link "Back", to: reorder_admin_path(@conn, :index),class: "btn btn-gold btn-gold"  %></span>

<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">reorder</h4>
        <p class="category"><%= link "Dashboard", to: retail_admin_dashboard_path(@conn, :index) %>/reorder/add</p>

    </div>
<%= render "form.html", Map.put(assigns, :action, reorder_admin_path(@conn, :create)) %>

lib/thamani_web/templates/reorder_admin/show.html.eex
<div class="row">
             <div class="col-md-12">


                           <span><%= link "Back", to: reorder_admin_path(@conn, :index), class: "btn btn-gold btn-gold" %></span>
                           <div class="card">
                               <div class="card-header" data-background-color="gold">
                                   <h4 class="title">Reorder</h4>
                                   <p class="category"><%= link "Dashboard", to: manufacturer_admin_dashboard_path(@conn, :index) %>/ reorder/ Show </p>

                               </div>

                               <table class="table" style="margin-left: 15px;">
                                 <tbody>


                               <tr>
                                 <td>SKU name:
                                 <%= @reorder.sku.gtin %></td>
                               </tr>

                               <tr>
                                 <td>Quantity:
                                 <%= @reorder.quantity %></td>
                               </tr>

                               <tr>
                                 <td>Type:
                                 <%= @reorder.type %></td>
                               </tr>

                               <tr>
                                 <td>manufacturer:
                                 <%= @reorder.manufacturer.company %></td>
                               </tr>

                               <tr>
                                 <%= if @reorder.wid == 0 do %>
                                   <td>Warehouse: N/A</td>
                                  <% else  %>
                                  <td>Warehouse: <%= @reorder.warehouse.company %> </td>
                                    <% end %>
                               </tr>


                               <tr>
                                 <td>description:
                                 <%= @reorder.description %></td>
                               </tr>

                               <tr>
                                 <td>Date of reorder:
                                 <%= @reorder.inserted_at %></td>
                               </tr>

                               <tr>
                                 <%= if @reorder.active == "true" do %>
                                 <td><p class = "btn btn-success btn-success" >Recieved</p></td>
                                   <% else  %>
                                   <td><p class = "btn btn-info btn-info" >Pending</p></td>
                                     <% end  %>
                               </tr>
                             </tbody>
                              </table>
                            </div>
                          </div>


<ul>

</ul>

</div>