lib/thamani_web/router.ex
      get("/:security_key/:user_id/:id", InventoryApiController, :show)
      post("/", InventoryApiController, :create)
      delete("/:id", InventoryApiController, :delete)
      put("/:id", InventoryApiController, :update)
    end

    scope "/push_sale" do
      pipe_through([:api])
      get("/:user_id", SaleApiController, :index)
      get("/:user_id/:id", SaleApiController, :show)
      post("/", SaleApiController, :create)
      delete("/:id", SaleApiController, :delete)
      put("/:id", SaleApiController, :update)
    end

    scope "/credit_note" do
      pipe_through([:api])
      get("/:security_key/:user_id", CreditnoteApiController, :index)
      get("/:security_key/:user_id/:id", CreditnoteApiController, :show)
      post("/", CreditnoteApiController, :create)
    end

    scope "/staff/retailer" do
      pipe_through([:api])
      get("/:security_key", StaffApiController, :index)
      get("/:security_key/:phone/:passcode", StaffApiController, :show)
      post("/", StaffApiController, :create)
      delete("/:id", StaffApiController, :delete)
      put("/:id", StaffApiController, :update)
    end

    scope "/device/retailer" do
      pipe_through([:api])
      get("/:security_key", DeviceApiController, :index)
      get("/:security_key/:imei", DeviceApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:api])

      get("/validate", ValidateApiController, :index)
      post("/validate", ValidateApiController, :create)
      post("/balance", BalanceApiController, :create)
      post("/status", MpesaStatusController, :create)
    end

    scope "/commerce" do
      pipe_through([:api])


      post("/cart", CommerceApiController, :create)
      post("/status", CommerceApiController, :status)
      post("/update", CommerceApiController, :updatecart)
      post("/del", CommerceApiController, :delcart)

    end

    scope "/stkpush" do
      pipe_through([:api])

      get("/validate", MpesaApiController, :index)
      post("/", MpesaApiController, :create)
      get("/validate/:params", MpesaApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:browser])
      resources("/sms/", SmsApiController)
      resources("/confirmation", ConfirmationController)
    end

    scope "/api/sale_url/v1" do
      pipe_through([:api])
      get("/:security_key", SaleDashboardApiController, :index)
      get("/:security_key/:account_number", SaleDashboardApiController, :show)
      post("/", SaleDashboardApiController, :create)
    end

    pipe_through([:browser, :with_session])

    get("/", PageController, :index)
    get("/privacy", PrivacyController, :index)
    get("/terms", TermsController, :index)
    resources("/register", RegisterController)
    resources("/login", LoginController, only: [:index, :create, :delete])

    resources(
      "/forgot_password",
      ResetController,
      only: [:index, :new, :create, :edit, :update, :delete]
    )

    scope "/" do
      pipe_through([:login_required])

      resources("/validation/", PaymentApiController)
      get("/panel", PanelController, :index)
      resources("/locations", LocationsController)
      resources("/sms_reset/", SmsResetController)
      resources(
        "/users",
        ChangePassController,
        only: [:update]
      )
      resources("/users", UserController)
      resources("/verify", VerifyController)

      # manufacturer panel
      resources("/manufacturer/dashboard/status", ManufacturerDashboardController)
      resources("/item", ItemController)
      resources("/batch", BatchController)
      resources("/manufacturer/dispatch/warehouse", DispatchController)
      resources("/manufacturer/dispatch/retailer", DispatchRetailerController)
      resources("/orders/warehouse/items", OrdersManufacturerController)
      resources("/orders/retail/items", OrdersRetmanController)
      resources("/invoice", InvoiceController)
      resources("/manufacturer/reorders/items", ReorderManufacturerController)
      resources("/manufacturer/sales/status", SalesManufacturerController)
      resources("/manufacturer/warehouse/returns", WreturnController)
      resources("/manufacturer/retailer/returns", RreturnController)
      resources("/manufacturer/warehouse/stock", StockManufacturerController)
      resources("/manufacturer/retailer/stock", StockRetmanController)


      resources "/manufacturer", UserController, only: [:show] do
        resources("/code", CodesController)
        resources("/company", CompanyController)
      end

      # warehouse Panel
      resources("/warehouse/dashboard/status", WarehouseDashboardController)
      resources("/invoice_warehouse", InvoiceWarehouseController)
      resources("/orders", OrdersWarehouseController)
      resources("/warehouse/recieved/items", RecievedController)
      resources("/storage", StorageController)
      resources("/break_bulk", BreakbulkController)
      resources("/warehouse/sales/status", SalesWarehouseController)
      resources("/dispatch", DispatchWarehouseController)
      resources("/manufacturer/order/items", ManufacturerOrdersController)
      resources("/returns", ReturnController)
      resources("/warehouse/reorders/items", ReorderWarehouseController)
      resources("/warehouse/retailer/stock", StockWarehouseController)

      # retailer panel
      resources("/retail/dashboard/status", RetailDashboardController)
      resources("/invoice_retailer", InvoiceRetailController)
      resources("/retailer/sales/status", SaleController)
      resources("/retailer/recieved/manufacturer", RecievedRetmanController)
      resources("/retailer/recieved/warehouse", RecievedRetailerController)
      resources("/inventory", InventoryController)
      resources("/inventory_manufacturer", Inventory2Controller)
      resources("/warehouse/orders/items", WarehouseOrdersController)
      resources("/retailer/orders/items", RetmanOrdersController)
      resources("/warehouse/returns/status", RetailReturnController)
      resources("/retailer/reorder/items", ReorderController)
      resources("/discount", DiscountController)
      resources("/credit_note", NotesController)
      resources("/staff", StaffController)
      resources("/shop", ShopController)
      resources("/device", DeviceController)

      # commerce Dashboard

      resources("/order", CommerceController)
      # get("/completed", CommerceController, :orders)
      resources("/commerce", CommsController)

      get("/completed", CommsController, :orders)

      # sales Dashboard

      resources("/sales/dashboard/status", SaleDashboardController)

      # admin zone GS1 Dashboard
      resources("/admin/thamani/dashboard", Gs1DashboardController)
      resources("/admin/thamani/price_master", PmasterController)
      resources("/admin/thamani/reconciliation", ReconcileController,only: [:index])
      resources("/admin/thamani/mpesa_transactions", MpesaController)

      # admin manufacturer
      resources("/admin/dashboard", ManufacturerAdminDashboardController)
      resources("/admin/item", ItemAdminController)
      resources("/admin/batch", BatchAdminController)
      resources("/admin/barcode", BarcodeController)
      resources("/admin/dispatch", DispatchAdminController)
      resources("/admin/dispatch_retailer/", DispatchRetailerAdminController)
      resources("/admin/warehouse/orders/all", OrdersAdmManufacturerController)
      resources("/admin/retail/orders/all", OrdersAdminRetmanController)
      resources("/admin/sales", SalesAdminManufacturerController)
      resources("/admin/reorder", ReorderAdminController)
      resources("/admin/manufacturer/warehouse/returns", WreturnAdminController)
      resources("/admin/manufacturer/retailer/returns", RreturnAdminController)

      # admin warehouse
      resources("/admin/warehouse/dashboard", WarehouseAdminDashboardController)
      resources("/admin/warehouse/recieved", RecievedAdminController)
      resources("/admin/warehouse/storage", StorageAdminController)
      resources("/admin/warehouse/break_bulk", BreakbulkAdminController)
      resources("/admin/warehouse/dispatch", DispatchAdminWarehouseController)
      resources("/admin/warehouse/manufacturer/orders", ManufacturerAdmOrdersController)
      resources("/admin/warehouse/manufacturer/returns", ReturnAdminController)
      resources("/admin/retailer/orders", OrdersAdmWarehouseController)

      # admin retailer
      resources("/admin/retailer/dashboard", RetailAdminDashboardController)
      resources("/admin/retailer/recieved", RecievedAdminRetailerController)
      resources("/admin/retailer/inventory", InventoryAdminController)
      resources("/admin/retailer/sales", SaleAdminController)
      resources("/admin/retailer/staff", StaffAdminController)
      resources("/admin/manufacturer/orders", RetmanAdminOrdersController)
      resources("/admin/retailer/shop", ShopAdminController)
      resources("/admin/retailer/device", DeviceAdminController)
      resources("/admin/retailer/discount", DiscountAdminController)
      resources("/admin/credit_note", NotesAdminController)
      resources("/admin/retailer/warehouse/orders", WarehouseAdmOrdersController)
      resources("/admin/retailer/returns", RetailAdminReturnController)

      # float panel

      resources("/float/dashboard", FloatDashboardController)
      resources("/float/credit", FloatController)

      resources "/float", UserController, only: [:show] do
        resources("/debit", DebitController)
      end

      # float admin panel
      resources("/admin/float/credit", FloatAdminController)
      resources("/admin/float/debit", DebitAdminController)
      resources("/admin/float/dashboard", FloatAdminDashboardController)

      # admin zone
      scope "/admin", Admin, as: :admin do
        pipe_through([:admin_required])

        resources "/users", UserController, only: [:index, :show] do
        end
      end
    end
  end

  # Other scopes may use custom stacks.

lib/thamani_web/controllers/rreturn_admin_controller.ex
defmodule ThamaniWeb.RreturnAdminController do
  use ThamaniWeb, :controller
  require Ecto.Query
  require Ecto
  use Ecto.Schema
  alias Thamani.Retail_Returns.Retail_Return
  alias Thamani.Retail_Returns
  alias Thamani.Returns
  alias Thamani.Inventories
  alias Thamani.Dispatches
  alias Thamani.Manufacturer_orders
  alias Thamani.Retman_orders
  alias Thamani.Repo

  plug(:put_layout, "manufacturer.html")
  plug(:scrub_params, "retail__return" when action in [:create, :update])

  def index(conn, _params) do
    recieved = Retail_Returns.list_retail_returns()
    count_order = Manufacturer_orders.get_count_order_all()
    count_order_retman = Retman_orders.get_count_order_all()
    count_stock = Inventories.get_count_restock_man_all()
    count_return = Returns.get_count_recieved_all()
    count_return_retail = Retail_Returns.get_count_recieved_all()

    render(
      conn,
      "index.html",
      recieved: recieved,
      count_stock: count_stock,
      count_order: count_order,
      count_order_retman: count_order_retman,
      count_return_retail: count_return_retail,
      count_return: count_return
    )
  end

  def show(conn, %{"id" => id}) do
    count_order = Manufacturer_orders.get_count_order_all()
    count_order_retman = Retman_orders.get_count_order_all()
    count_stock = Inventories.get_count_restock_man_all()
    count_return = Returns.get_count_recieved_all()
    count_return_retail = Retail_Returns.get_count_recieved_all()
    recieved = Retail_Returns.get_retail_return!(id)

    render(
      conn,
      "show.html",
      recieved: recieved,
      count_stock: count_stock,
      count_order: count_order,
      count_order_retman: count_order_retman,
      count_return_retail: count_return_retail,
      count_return: count_return
    )
  end

  def edit(conn, %{"return_id" => companies, "id" => id}, current_user) do
    recieved = Retail_Returns.get_recieved(companies, id)
    bat = Inventories.get_items(current_user)
    count_stock = Inventories.get_count_restock_man(current_user)
    count_order = Manufacturer_orders.get_count_order(current_user)
    count_order_retman = Retman_orders.get_count_order(current_user)
    count_return_retail = Retail_Returns.get_count_recieved(current_user)
    count_return = Returns.get_count_recieved(current_user)
    company = Dispatches.get_company()

    if recieved do
      changeset = Retail_Return.changeset(recieved, %{})

      render(
        conn,
        "edit.html",
        recieved: recieved,
        changeset: changeset,
        bat: bat,
        company: company,
        count_stock: count_stock,
        count_order: count_order,
        count_order_retman: count_order_retman,
        count_return_retail: count_return_retail,
        count_return: count_return
      )
    else
      conn
      |> put_flash(:error, "Not authorised to edit this page")
      |> redirect(to: rreturn_path(conn, :index))
    end
  end

  def update(
        conn,
        %{"return_id" => companies, "id" => id, "retail__return" => recieved_params},
        current_user
      ) do
    recieved = Retail_Returns.get_recieved(companies, id)
    count_stock = Inventories.get_count_restock_man(current_user)
    count_order = Manufacturer_orders.get_count_order(current_user)
    count_order_retman = Retman_orders.get_count_order(current_user)
    count_return_retail = Retail_Returns.get_count_recieved(current_user)
    count_return = Returns.get_count_recieved(current_user)
    changeset = Retail_Return.changeset(recieved, recieved_params)

    case Repo.update(changeset) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "recieved updated successfully.")
        |> redirect(to: rreturn_path(conn, :index))

      {:error, changeset} ->
        render(
          conn,
          "edit.html",
          recieved: recieved,
          changeset: changeset,
          count_stock: count_stock,
          count_order: count_order,
          count_order_retman: count_order_retman,
          count_return_retail: count_return_retail,
          count_return: count_return
        )
    end
  end
end

lib/thamani_web/views/rreturn_admin_view.ex
defmodule ThamaniWeb.RreturnAdminView do
  use ThamaniWeb, :view
  use Rummage.Phoenix.View
end

lib/thamani_web/templates/rreturn_admin/edit.html.eex
<span class="col-md-10" style="margin-left: -25px;"> <%= link "Back", to: rreturn_path(@conn, :index),class: "btn btn-gold btn-gold"  %></span>

<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">Return</h4>
        <p class="category"><%= link "Dashboard", to: rreturn_path(@conn, :index) %>/ Return/edit</p>

    </div>
<%= render "form.html", Map.put(assigns, :action, rreturn_path(@conn, :update, @recieved)) %>

lib/thamani_web/templates/rreturn_admin/form.html.eex
<%= form_for @changeset, @action, [multipart: true] , fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <div class="col-md-6">
  <div class="form-group label-floating">
    <%= label f, :"SKU Item", class: "control-label" %>
    <%= text_input f, :gtin , class: "form-control",  required: "required" , disabled: "disabled", value: @recieved.sku.gtin <> "(" <> @recieved.sku.name<>")"%>
      </div>
    <%= error_tag f, :gtin %>
  </div>


  <div class="col-md-6">
    <div class="form-group label-floating">
    <%= label f, :Quantity, class: "control-label" %>
    <%= number_input f, :quantity, class: "form-control" , disabled: "disabled"%>
      </div>
    <%= error_tag f, :quantity %>
  </div>
  <div class="col-md-10">
    <div class="form-group label-floating">
    <%= label f, :"Reason for return", class: "control-label" %>
    <%= textarea f, :description, class: "form-control", disabled: "disabled" %>
      </div>
    <%= error_tag f, :description %>
  </div>

  <div class="col-md-10">
    <div class="form-group label-floating">
    <%= label f, :"Issue Status", class: "control-label" %>
    <%= checkbox f, :active, class: "checkbox-material" , disabled: "disabled"%>
      </div>
    <%= error_tag f, :active %>
  </div>

  <hr></hr>
  <div class="col-md-10">
    <div class="form-group label-floating">
    <%= label f, :"Comments to Retailer", class: "control-label" %>
    <%= textarea f, :comments, class: "form-control" %>
      </div>
    <%= error_tag f, :comments %>
  </div>




  <div class="col-md-6">
    <div class="form-group label-floating">
    <%= submit "Submit", class: "btn btn-gold" %>
  </div>
    </div>
<% end %>

lib/thamani_web/templates/rreturn_admin/index.html.eex
                                            <div class="row">
                                                                   <div class="col-md-12">

                                                                       <div class="card">
                                                                           <div class="card-header" data-background-color="gold">
                                                                               <h4 class="title">Return From Retailer</h4>
                                                                               <p class="category"><%= link "Dashboard", to: manufacturer_admin_dashboard_path(@conn, :index) %>/return</p>

                                                                           </div>

                                                                           <div class="card-content table-responsive">
                                                                             <div id="toolbar" style="margin-top: -16px;">
                                                                            <select class="form-control">
                                                                              <option value="">Export Current page</option>
                                                                              <option value="all">Export All</option>
                                                                              <option value="selected">Export Selected</option>
                                                                            </select>
                                                                          </div>
                                          <table class="table" id ="fresh-table" data-toggle="table" data-toolbar="#toolbar" data-search="true"  data-pagination="true" data-show-print="true" data-show-export="true"   data-export-options='{"fileName": "reports"}'>
                                              <thead class="text-info">
                                                <tr>
                                                  <th data-field="state" data-checkbox="true"></th>
                                                  <th data-field="item" data-sortable="true">SKU</th>
                                                  <th data-field="company" data-sortable="true">From</th>
                                                  <th data-field="co" data-sortable="true">To</th>
                                                  <th data-field="quantity" data-sortable="true">Quantity</th>
                                                  <th data-field="production" data-sortable="true">Description</th>

                                                  <th class="text-center" >Issue Status</th>
                                                  <th class="text-center"> Actions</th>
                                                </tr>
                                              </thead>
                                              <tbody>
                                            <%= for recieved <- @recieved do %>
                                                <tr>
                                                  <td></td>
                                                  <td><%= recieved.sku.gtin %>(<%= recieved.sku.name %>) </td>
                                                  <td><%= recieved.user.company %> </td>
                                                  <td><%= recieved.companies.company %> </td>
                                                  <td><%= recieved.quantity %> </td>
                                                  <td><%= recieved.description %> </td>



                                                  <%= if recieved.active == "true" do %>
                                                    <td><i class="fa fa-check" style= "color:#66bb6a !important"></i></td>
                                                  <% else  %>
                                                  <td><i class="fa fa-close" style= "color:#f44336 !important"></i></td>
                                                  <% end %>
                                                  <td class="text-right">
                                                  <span  rel="tooltip" title="View Task" class="btn btn-info btn-simple ">
                                                      <span ><%= link "",  to: rreturn_admin_path(@conn, :show, recieved), class: "fa fa-search-plus" ,style: "color:#00bcd4 !important" %></span>
                                                  </span>



</td>

    </tr>
<% end %>
  </tbody>
</table>
</div>
                                                        </div>
                                                      </div>
                                                    </div>

lib/thamani_web/templates/rreturn_admin/new.html.eex
<span class="col-md-10" style="margin-left: -25px;"> <%= link "Back", to: rreturn_path(@conn, :index),class: "btn btn-gold btn-gold"  %></span>

<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">return</h4>
        <p class="category"><%= link "Dashboard", to: rreturn_path(@conn, :index) %>/ return /add</p>

    </div>
<%= render "form.html", Map.put(assigns, :action, rreturn_path(@conn, :create)) %>

lib/thamani_web/templates/rreturn_admin/show.html.eex
<div class="row">
           <div class="col-md-12">


                           <span><%= link "Back", to: rreturn_admin_path(@conn, :index), class: "btn btn-gold btn-gold" %></span>
                           <div class="card">
                               <div class="card-header" data-background-color="gold">
                                   <h4 class="title">Return From Retailer</h4>
                                   <p class="category"><%= link "Dashboard", to: manufacturer_admin_dashboard_path(@conn, :index) %>/ return / Show </p>

                               </div>

                               <table class="table" style="margin-left: 15px;">
                                    <tbody>


  <tr>
    <td>SKU:
    <%= @recieved.sku.gtin %>(<%= @recieved.sku.name %>)</td>
  </tr>
  <tr>
    <td>Quantity:
    <%= @recieved.quantity %></td>
  </tr>
  <tr>
    <td>Company:
    <%= @recieved.companies.company %></td>
  </tr>
  <tr>
    <td>description:
    <%= @recieved.description %></td>
  </tr>
  <tr>
    <td>description:
    <%= @recieved.description %></td>
  </tr>
  <tr>
    <td>Comments:
    <%= @recieved.comments %></td>
  </tr>

  <tr>
    <td>Issue Status:
      <%= if @recieved.active == "true" do %>
        <i class="fa fa-check" style= "color:#66bb6a !important"></i>
      <% else  %>
      <i class="fa fa-close" style= "color:#f44336 !important"></i>
      <% end %>
  </tr>
</tbody>
                              </table>
                            </div>
                          </div>


<ul>

</ul>

</div>