lib/thamani_web/router.ex
defmodule ThamaniWeb.Router do
  use ThamaniWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(JaSerializer.Deserializer)
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:accepts, ["json-api"])
  end

  pipeline :with_session do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
    plug(ThamaniWeb.CurrentUser)
  end

  pipeline :login_required do
    plug(
      Guardian.Plug.EnsureAuthenticated,
      handler: ThamaniWeb.GuardianErrorHandler
    )

    plug(
      ThamaniWeb.LoginTimeout,
      timeout_after_seconds: 3600
    )
  end

  pipeline :admin_required do
    plug(ThamaniWeb.CheckAdmin)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/", ThamaniWeb do
    scope "/push" do
      pipe_through([:api])

      get("/:security_key/:user_id", InventoryApiController, :index)
      get("/:security_key/:user_id/:id", InventoryApiController, :show)
      post("/", InventoryApiController, :create)
      delete("/:id", InventoryApiController, :delete)
      put("/:id", InventoryApiController, :update)
    end

    scope "/push_sale" do
      pipe_through([:api])
      get("/:user_id", SaleApiController, :index)
      get("/:user_id/:id", SaleApiController, :show)
      post("/", SaleApiController, :create)
      delete("/:id", SaleApiController, :delete)
      put("/:id", SaleApiController, :update)
    end

    scope "/credit_note" do
      pipe_through([:api])
      get("/:security_key/:user_id", CreditnoteApiController, :index)
      get("/:security_key/:user_id/:id", CreditnoteApiController, :show)
      post("/", CreditnoteApiController, :create)
    end

    scope "/staff/retailer" do
      pipe_through([:api])
      get("/:security_key", StaffApiController, :index)
      get("/:security_key/:phone/:passcode", StaffApiController, :show)
      post("/", StaffApiController, :create)
      delete("/:id", StaffApiController, :delete)
      put("/:id", StaffApiController, :update)
    end

    scope "/device/retailer" do
      pipe_through([:api])
      get("/:security_key", DeviceApiController, :index)
      get("/:security_key/:imei", DeviceApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:api])

      get("/validate", ValidateApiController, :index)
      post("/validate", ValidateApiController, :create)
      post("/balance", BalanceApiController, :create)
      post("/status", MpesaStatusController, :create)
    end

    scope "/commerce" do
      pipe_through([:api])


      post("/cart", CommerceApiController, :create)
      post("/status", CommerceApiController, :status)
      post("/update", CommerceApiController, :updatecart)
      post("/del", CommerceApiController, :delcart)

    end

    scope "/stkpush" do
      pipe_through([:api])

      get("/validate", MpesaApiController, :index)
      post("/", MpesaApiController, :create)
      get("/validate/:params", MpesaApiController, :show)
    end

    scope "/callbacks" do
      pipe_through([:browser])
      resources("/sms/", SmsApiController)
      resources("/confirmation", ConfirmationController)
    end

    scope "/api/sale_url/v1" do
      pipe_through([:api])
      get("/:security_key", SaleDashboardApiController, :index)
      get("/:security_key/:account_number", SaleDashboardApiController, :show)
      post("/", SaleDashboardApiController, :create)
    end

    pipe_through([:browser, :with_session])

    get("/", PageController, :index)
    get("/privacy", PrivacyController, :index)
    get("/terms", TermsController, :index)
    resources("/register", RegisterController)
    resources("/login", LoginController, only: [:index, :create, :delete])

    resources(
      "/forgot_password",
      ResetController,
      only: [:index, :new, :create, :edit, :update, :delete]
    )

    scope "/" do
      pipe_through([:login_required])

      resources("/validation/", PaymentApiController)
      get("/panel", PanelController, :index)
      resources("/locations", LocationsController)
      resources("/sms_reset/", SmsResetController)
      resources(
        "/users",
        ChangePassController,
        only: [:update]
      )
      resources("/users", UserController)
      resources("/verify", VerifyController)

      # manufacturer panel
      resources("/manufacturer/dashboard/status", ManufacturerDashboardController)
      resources("/item", ItemController)
      resources("/batch", BatchController)
      resources("/manufacturer/dispatch/warehouse", DispatchController)
      resources("/manufacturer/dispatch/retailer", DispatchRetailerController)
      resources("/orders/warehouse/items", OrdersManufacturerController)
      resources("/orders/retail/items", OrdersRetmanController)
      resources("/invoice", InvoiceController)
      resources("/manufacturer/reorders/items", ReorderManufacturerController)
      resources("/manufacturer/sales/status", SalesManufacturerController)
      resources("/manufacturer/warehouse/returns", WreturnController)
      resources("/manufacturer/retailer/returns", RreturnController)
      resources("/manufacturer/warehouse/stock", StockManufacturerController)
      resources("/manufacturer/retailer/stock", StockRetmanController)


      resources "/manufacturer", UserController, only: [:show] do
        resources("/code", CodesController)
        resources("/company", CompanyController)
      end

      # warehouse Panel
      resources("/warehouse/dashboard/status", WarehouseDashboardController)
      resources("/invoice_warehouse", InvoiceWarehouseController)
      resources("/orders", OrdersWarehouseController)
      resources("/warehouse/recieved/items", RecievedController)
      resources("/storage", StorageController)
      resources("/break_bulk", BreakbulkController)
      resources("/warehouse/sales/status", SalesWarehouseController)
      resources("/dispatch", DispatchWarehouseController)
      resources("/manufacturer/order/items", ManufacturerOrdersController)
      resources("/returns", ReturnController)
      resources("/warehouse/reorders/items", ReorderWarehouseController)
      resources("/warehouse/retailer/stock", StockWarehouseController)

      # retailer panel
      resources("/retail/dashboard/status", RetailDashboardController)
      resources("/invoice_retailer", InvoiceRetailController)
      resources("/retailer/sales/status", SaleController)
      resources("/retailer/recieved/manufacturer", RecievedRetmanController)
      resources("/retailer/recieved/warehouse", RecievedRetailerController)
      resources("/inventory", InventoryController)
      resources("/inventory_manufacturer", Inventory2Controller)
      resources("/warehouse/orders/items", WarehouseOrdersController)
      resources("/retailer/orders/items", RetmanOrdersController)
      resources("/warehouse/returns/status", RetailReturnController)
      resources("/retailer/reorder/items", ReorderController)
      resources("/discount", DiscountController)
      resources("/credit_note", NotesController)
      resources("/staff", StaffController)
      resources("/shop", ShopController)
      resources("/device", DeviceController)

      # commerce Dashboard

      resources("/order", CommerceController)
      # get("/completed", CommerceController, :orders)
      resources("/commerce", CommsController)

      get("/completed", CommsController, :orders)

      # sales Dashboard

      resources("/sales/dashboard/status", SaleDashboardController)

      # admin zone GS1 Dashboard
      resources("/admin/thamani/dashboard", Gs1DashboardController)
      resources("/admin/thamani/price_master", PmasterController)
      resources("/admin/thamani/reconciliation", ReconcileController,only: [:index])
      resources("/admin/thamani/mpesa_transactions", MpesaController)

      # admin manufacturer
      resources("/admin/dashboard", ManufacturerAdminDashboardController)
      resources("/admin/item", ItemAdminController)
      resources("/admin/batch", BatchAdminController)
      resources("/admin/barcode", BarcodeController)
      resources("/admin/dispatch", DispatchAdminController)
      resources("/admin/dispatch_retailer/", DispatchRetailerAdminController)
      resources("/admin/warehouse/orders/all", OrdersAdmManufacturerController)
      resources("/admin/retail/orders/all", OrdersAdminRetmanController)
      resources("/admin/sales", SalesAdminManufacturerController)
      resources("/admin/reorder", ReorderAdminController)
      resources("/admin/manufacturer/warehouse/returns", WreturnAdminController)
      resources("/admin/manufacturer/retailer/returns", RreturnAdminController)

      # admin warehouse
      resources("/admin/warehouse/dashboard", WarehouseAdminDashboardController)
      resources("/admin/warehouse/recieved", RecievedAdminController)
      resources("/admin/warehouse/storage", StorageAdminController)
      resources("/admin/warehouse/break_bulk", BreakbulkAdminController)
      resources("/admin/warehouse/dispatch", DispatchAdminWarehouseController)
      resources("/admin/warehouse/manufacturer/orders", ManufacturerAdmOrdersController)
      resources("/admin/warehouse/manufacturer/returns", ReturnAdminController)
      resources("/admin/retailer/orders", OrdersAdmWarehouseController)

      # admin retailer
      resources("/admin/retailer/dashboard", RetailAdminDashboardController)
      resources("/admin/retailer/recieved", RecievedAdminRetailerController)
      resources("/admin/retailer/inventory", InventoryAdminController)
      resources("/admin/retailer/sales", SaleAdminController)
      resources("/admin/retailer/staff", StaffAdminController)
      resources("/admin/manufacturer/orders", RetmanAdminOrdersController)
      resources("/admin/retailer/shop", ShopAdminController)

lib/thamani/inventories/inventory.ex
defmodule Thamani.Inventories.Inventory do
  use Ecto.Schema
  import Ecto.Changeset
  alias Thamani.Items.Sku
  alias Thamani.Discounts.Discount
  alias Thamani.Accounts.User

  schema "inventories" do
    field(:active, :string)
    field(:confirm, :string)
    field(:category, :string)
    field(:description, :string)
    field(:quantity, :integer)
    field(:sold, :decimal)
    field(:remain, :integer)
    field(:reorderstock, :integer)
    field(:reorderlevel, :integer)
    field(:batch, :string)
    field(:expiry, :string)
    field(:production, :string)
    field(:breakbulk_code, :integer)
    field(:recieved_id, :integer)
    field(:type, :string)
    field(:manufacturer, :float)
    field(:mid, :integer)
    field(:warehouse, :float)
    field(:wid, :integer)
    field(:gs1, :float)
    belongs_to(:discounts, Discount, foreign_key: :discount)
    belongs_to(:sku, Sku, foreign_key: :item)
    field(:price, :string)
    belongs_to(:user, User, foreign_key: :user_id)

    timestamps()
  end

  @doc false
  def changeset(inventory, attrs) do
    inventory
    |> cast(attrs, [
      :item,
      :manufacturer,
      :mid,
      :discount,
      :warehouse,
      :wid,
      :gs1,
      :price,
      :category,
      :description,
      :reorderstock,
      :reorderlevel,
      :batch,
      :expiry,
      :production,
      :breakbulk_code,
      :recieved_id,
      :type,
      :quantity,
      :sold,
      :remain,
      :active,
      :confirm,
      :user_id
    ])
    |> validate_required([:item, :price, :active])
  end
end

lib/thamani_web/views/inventory_view.ex
defmodule ThamaniWeb.InventoryView do
  use ThamaniWeb, :view
end

lib/thamani_web/templates/inventory/edit.html.eex
<% alias Thamani.Sales
   alias Thamani.Dispatches
   alias Thamani.Pmasters
   alias Thamani.Inventories
   alias Thamani.Sales
 %>
<div class="col-md-12">
  <span><%= link "Back", to: inventory_path(@conn, :index), class: "btn btn-gold btn-gold" %></span>

  <div class="card">
      <div class="card-header" data-background-color="gold">
          <h4 class="title"><%=@inventory.sku.name %> Price range</h4>

      </div>

     <table class="table"  style="margin-left: 0px;">
       <thead class="text-info">
         <tr>
           <th data-field="batch" data-sortable="true"> Price Buildup</th>
           <th data-field="expiry" data-sortable="true">Range allowable</th>
           <th data-field="production" data-sortable="true">Price addition Alowable #</th>
          <th data-field="price" data-sortable="true">Final Price Buildup</th>

          </tr>
          </thead>
          <tbody>

<td><span style ="background:#66bb6a !important;padding: 5px;border-radius: 5px;font-size: 13px;"> <%= Float.ceil(String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ,2) %></span></td>



  <td><span style ="background:#f44336 !important;padding: 5px;border-radius: 5px;font-size: 13px;"><%= Pmasters.get_min(Dispatches.getcategoryname(@inventory.item))%>% - <%= Pmasters.get_max(Dispatches.getcategoryname(@inventory.item))%>%</span></td>




   <td><span style ="background:gold !important;padding: 5px;border-radius: 5px;font-size: 13px;">
     <%= Float.ceil( (Pmasters.get_min(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ),2)%> -

 <%= Float.ceil( (Pmasters.get_max(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ),2)%> </span></td>



    <td><span style ="background:#66bb6a !important;padding: 5px;border-radius: 5px;font-size: 13px;">
     <%= Float.ceil(Float.ceil(String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ,2) +
     Float.ceil( (Pmasters.get_min(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ) ,2),2)%> -
    <%= Float.ceil(Float.ceil(String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ,2) +
    Float.ceil( (Pmasters.get_max(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(@inventory.item, @current_user)) ) ,2),2)%> </span></td>



                                         </tbody>
                                   </table>
   </div>

   </div>
<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">Inventory</h4>
        <p class="category"><%= link "Dashboard", to: inventory_path(@conn, :index) %>/ inventory/edit</p>

    </div>
    <%= form_for @changeset, inventory_path(@conn, :update, @inventory), [multipart: true] , fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="col-md-6">
        <div class="form-group label-floating">
        <%= label f, :item, class: "control-label" %>
        <input  class="form-control select-with-transition"  value="<%= @inventory.sku.name %>" disabled="disabled"/>
          <%= text_input f, :item, class: "form-control" ,type: "hidden" %>
    </div>

        <%= error_tag f, :item %>
      </div>


      <div class="col-md-5">
        <div class="form-group label-floating spinner" data-trigger="spinner">
        <%= label f, :"price format i.e 100.00 or 100.5 0r 100.25", class: "control-label" %>
        <%= text_input f, :price, class: "form-control" , "data-rule": "currency"%>
        <button type="button" data-spin="up">+</button>
      <button type="button" data-spin="down">-</button>
          </div>


        <%= error_tag f, :price %>
      </div>

        <div class="col-md-6">
      <div class="form-group label-floating">
        <%= label f, :"Discount", class: "control-label" %>
        <%= select f, :discount, @discount, class: "single_select", style: "width: 100%", title: "Choose item" %>
          </div>
        <%= error_tag f, :discount %>
      </div>
      <div class="col-md-6">
        <div class="form-group label-floating spinner" data-trigger="spinner">
        <%= label f, :"reorder level threshold", class: "control-label" %>
        <%= text_input f, :reorderlevel, class: "form-control" , "data-rule": "quantity" , "data-max": "null" %>
        <button type="button" data-spin="up">+</button>
      <button type="button" data-spin="down">-</button>
          </div>

        <%= error_tag f, :reorderlevel %>
      </div>
      <div class="col-md-6">
        <div class="form-group label-floating spinner" data-trigger="spinner">
        <%= label f, :"reorder stock", class: "control-label" %>
        <%= text_input f, :reorderstock, class: "form-control" , "data-rule": "quantity" , "data-max": "null" %>
        <button type="button" data-spin="up">+</button>
      <button type="button" data-spin="down">-</button>
          </div>

        <%= error_tag f, :reorderstock %>
      </div>



      <div class="col-md-10">
        <div class="form-group label-floating">
        <%= label f, :description, class: "control-label" %>
        <%= textarea f, :description, class: "form-control" %>
          </div>
        <%= error_tag f, :description %>
      </div>





      <div class="col-md-10">
        <div class="form-group label-floating">

        <%= label f, :active, class: "control-label" %>
        <%= checkbox f, :active, class: "checkbox-material" %>
          </div>
        <%= error_tag f, :active %>
      </div>

      <div class="col-md-6">
        <div class="form-group label-floating">
        <%= submit "Submit", class: "btn btn-gold" %>
      </div>
        </div>
    <% end %>

lib/thamani_web/templates/inventory/new.html.eex
<span class="col-md-10" style="margin-left: -25px;"> <%= link "Back", to: inventory_path(@conn, :index),class: "btn btn-gold btn-gold"  %></span>

<div class="card" style="margin:25px -10px">
    <div class="card-header" data-background-color="gold">
        <h4 class="title">inventory</h4>
        <p class="category"><%= link "Dashboard", to: inventory_path(@conn, :index) %>/inventory/add</p>

    </div>
<%= render "form.html", Map.put(assigns, :action, inventory_path(@conn, :create)) %>

lib/thamani_web/templates/inventory/show.html.eex
<% alias Thamani.Sales
   alias Thamani.Dispatches
   alias Thamani.Pmasters
   alias Thamani.Inventories
 %>
<div class="row">
                 <%= if @current_user.id == @user.id do %>
                  <div class="col-md-8">
                 <div class="col-md-12">
                   <span><%= link "Edit inventory", to: inventory_path(@conn, :edit, @inventory) , class: "btn btn-gold btn-gold" %></span>
                   <span><%= link "Back", to: inventory_path(@conn, :index), class: "btn btn-gold btn-gold" %></span>

                   <div class="card">
                       <div class="card-header" data-background-color="gold">
                         <%= if is_nil(@inventory.sku) do %>
                         <h4 class="title">Deleted</h4>
                         <% else %>
                           <h4 class="title"><%= @inventory.sku.name %> Price range</h4>
                          <% end %>
                       </div>
                      <%= for inventories_price <- @inventories_price do %>

                      <table class="table"  style="margin-left: 0px;">
                        <thead class="text-info">
                          <tr>
                            <th data-field="batch" data-sortable="true"> Price Buildup</th>
                            <th data-field="expiry" data-sortable="true">Range allowable</th>
                            <th data-field="production" data-sortable="true">Price addition Alowable #</th>
                           <th data-field="price" data-sortable="true">Final Price Buildup</th>

                           </tr>
                           </thead>
                           <tbody>

                 <td><span style ="background:#66bb6a !important;padding: 5px;border-radius: 5px;font-size: 13px;"> <%= Float.ceil(String.to_float(Dispatches.get_price(inventories_price.item)) + Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(inventories_price.item, @current_user) ),2) %></span></td>



                   <td><span style ="background:#f44336 !important;padding: 5px;border-radius: 5px;font-size: 13px;"><%= Pmasters.get_min(Dispatches.getcategoryname(inventories_price.item))%>% - <%= Pmasters.get_max(Dispatches.getcategoryname(inventories_price.item))%>%</span></td>



   <td><span style ="background:gold !important;padding: 5px;border-radius: 5px;font-size: 13px;">
     <%= Float.ceil( (Pmasters.get_min(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(inventories_price.item, @current_user)) ),2) %> -

 <%= Float.ceil( (Pmasters.get_max(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) +  (Inventories.get_item_warehouse(inventories_price.item, @current_user)) ),2)%> </span></td>



    <td><span style ="background:#66bb6a !important;padding: 5px;border-radius: 5px;font-size: 13px;">
     <%= Float.ceil(Float.ceil(String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(inventories_price.item, @current_user)),2)+
     Float.ceil( (Pmasters.get_min(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(inventories_price.item, @current_user)) ),2),2)%> -
  <%= Float.ceil( Float.ceil(String.to_float(Dispatches.get_price(@inventory.item)) + Float.ceil(Sales.get_gs1_value(),1)+ (Inventories.get_item_warehouse(inventories_price.item, @current_user)) ,2)+
  Float.ceil( (Pmasters.get_max(Dispatches.getcategoryname(@inventory.item))/100) * (String.to_float(Dispatches.get_price(@inventory.item))+ Float.ceil(Sales.get_gs1_value(),1) + (Inventories.get_item_warehouse(inventories_price.item, @current_user)) ),2),2)%> </span></td>


                                                          </tbody>
                                                    </table>
                    </div>
                        <% end %>
                    </div>

                 <div class="col-md-12">


                             <div class="card">
                               <div class="card-header" data-background-color="gold">
                                   <h4 class="title">Inventory</h4>
                                   <p class="category"><%= link "Dashboard", to: retail_dashboard_path(@conn, :index) %>/ inventory/ Show </p>

                               </div>
                               
                                 <div id="toolbar" style="margin-top: -16px;">
                                <select class="form-control">
                                  <option value="">Export Current page</option>
                                  <option value="all">Export All</option>
                                  <option value="selected">Export Selected</option>
                                </select>
                               </div>
                               <table class="table" id ="fresh-table" data-toggle="table" data-toolbar="#toolbar" data-search="true"  data-pagination="true" data-show-print="true" data-show-export="true"   data-export-options='{"fileName": "reports"}'>                                 <thead class="text-info">
                                   <tr>
                                     <th data-field="batch" data-sortable="true">Batch #</th>
                                     <th data-field="expiry" data-sortable="true">Days to Expiry</th>
                                     <th data-field="production" data-sortable="true">Production #</th>
                                    <th  data-sortable="true">Your Price</th>
                                    <th  data-sortable="true">Total Price</th>
				     <th data-field="available" data-sortable="true">Qty </th>

                                      <th class="text-center" >Actions</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                       <%= for inventories <- @inventories do %>
                                    <tr>
                                        <td><%= (inventories.batch) %> </td>
                                        <%= if Timex.diff(Date.from_iso8601!(inventories.expiry), DateTime.utc_now(), :days) > 0 do %>
                                            <%= if Timex.diff(Date.from_iso8601!(inventories.expiry), DateTime.utc_now(), :days) >= 60 do %>
                                                <td >
                                                <button type="button" class= 'btn btn-success btn-success' data-toggle="popover" data-trigger="hover" title="Date of Expiry" data-content= '<%=inventories.expiry %>' style="margin:20px;">
                                                <%= Timex.diff(Date.from_iso8601!(inventories.expiry), DateTime.utc_now(), :days)  %>
                                                </button>
                                                </td>
                                            <% else %>
                                                <td >
                                                  <button type="button" class= 'btn btn-success btn-danger' data-toggle="popover" data-trigger="hover" title="Date of Expiry" data-content= '<%=inventories.expiry %>' style="margin:20px;">
                                                  <%= Timex.diff(Date.from_iso8601!(inventories.expiry), DateTime.utc_now(), :days)  %>
                                                  </button>
                                              </td>
                                            <% end %>
                                        <% else %>
						<td>
                                           <button class= 'btn btn-success btn-danger' data-toggle="popover" data-trigger="hover" title="Date of Expiry" data-content= '<%=inventories.expiry %>' style="margin:20px;"> 0</button>
                                         </td>
                                       <% end %>

                                      <td><%= (inventories.production) %> </td>
                                    <td><%= (inventories.price) %> </td>
				      <td><%=Float.floor(String.to_float(inventories.price) + Float.ceil(Sales.get_gs1_value(),1) + (@inventory.manufacturer) + (@inventory.warehouse),2) %></td>

                                    <td><%= (inventories.quantity) %> </td>




                                    <td class="text-right">
                                      <span  rel="tooltip" title="Delete Task" class="btn btn-danger btn-simple ">
                                          <span><%= link "",to: inventory_path(@conn, :delete, inventories), method: :delete, data: [confirm: "Are you sure?"],  class: "fa fa-close", style: "color:#f44336 !important" %></span>
                                      </span>
                                    </td>

                                    <% end %>


                                    </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                          <div class="col-md-4">

              <div class="card card-profile" style="background:gold;">

                <div class="card-body" >
                  <h6 class="card-category text-gray">Details for</h6>
                  <h4 class="card-title"><%= @inventory.sku.name %></h4>
                  <table class="table" style="margin-left: 0px;">
                       <tbody>


                     <tr>
                       <td>SKU GTIN:
                       <%= @inventory.sku.gtin %></td>
                     </tr>

                     <tr>
                       <td>Name of inventory:
                       <%= @inventory.sku.name %></td>
                     </tr>

		     <tr>
			<td>Category:
			<%= Pmasters.getname(Dispatches.getcategoryname(@inventory.item)) %></td>
		     </tr>

                     <tr>
                       <td>My Price:
                       <%= @inventory.price %></td>
                     </tr>
			 <tr>
                       <td>Discount Price:
                       <%= (String.to_float(@inventory.price) - (String.to_float(@inventory.price) * (@inventory.discounts.value/100))) %></td>
                     </tr>
		      <tr>
                       <td>Current Total Price:
                       <%= Float.ceil( ( String.to_float(@inventory.price) - (String.to_float(@inventory.price) * (@inventory.discounts.value/100)) )  + Float.ceil(Sales.get_gs1_value(),1) + (@inventory.manufacturer) + (@inventory.warehouse),2) %></td>
                     </tr>
                     <tr>
                       <td>Discount:
                       <%= @inventory.discounts.name %> (<%= @inventory.discounts.value %>%)</td>
                     </tr>

                     <tr>
                       <td>Stock level threshold:
                       <%= @inventory.reorderlevel %> </td>
                     </tr>

                     <tr>
                       <td>Reorder stock quantity:
                       <%= @inventory.reorderstock %> </td>
                     </tr>


                     <tr>
                       <td>description:
                       <%= @inventory.description %></td>
                     </tr>

                     <tr>
                       <td>Active:
                         <%= if @inventory.active == "true" do %>
                           <i class="fa fa-check" style= "color:#66bb6a !important"></i>
                         <% else  %>
                         <i class="fa fa-close" style= "color:#f44336 !important"></i>
                         <% end %>
                     </tr>
		     <tr>
			<td>Image   <p> <img src="<%= Thamani.ImageUploader.url({@inventory.sku.image, @inventory})%>"  style="width:150px"></p>  </td>
		     </tr>
                   </tbody>
                 </table>
                </div>
              </div>
            </div>


<ul>


</ul>
<% else %>
    <h1>Not authorised to access this page</h1>
<% end %>
</div>